version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12.18.3
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Remove .git folder to decrease workspace size
          command: rm -rf .git
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: run-tests
          command: yarn test
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: run-lint
          command: yarn lint
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
